In [2]:
import torch
import numpy as np

## Intro

In [2]:
x = torch.tensor([1, 2, 3])
torch.sum(x)

tensor(6)

**torch.sum(input, dim, keepdim=False, dtype=None) → Tensor**

**numpy.sum(a, axis=None, dtype=None, out=None, keepdims=False)**

In [3]:
x = torch.tensor([
     [1, 2, 3],
     [4, 5, 6]
   ])

x.shape

torch.Size([2, 3])

In [16]:
y = torch.tensor([
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ]
   ])

y.shape

torch.Size([3, 2, 3])

### sum axis=0

![](https://miro.medium.com/v2/resize:fit:640/1*XvGIb1XxF6r9FYHQ3yYPTw.gif)

In [11]:
torch.sum(y, dim=0)

tensor([[ 3,  6,  9],
        [12, 15, 18]])

### sum axis=1

![](https://miro.medium.com/v2/resize:fit:640/1*e608vZqp7jNIdsarKbeunQ.gif)

In [12]:
torch.sum(y, dim=1)

tensor([[5, 7, 9],
        [5, 7, 9],
        [5, 7, 9]])

### sum axis=2

![](https://miro.medium.com/v2/resize:fit:640/1*pf9K7VX2M6_1p39JUmOkLQ.gif)

In [18]:
y

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [17]:
torch.sum(y, dim=2)

tensor([[ 6, 15],
        [ 6, 15],
        [ 6, 15]])

In [20]:
tensor_3d = y
tensor_3d.unsqueeze(0).shape

torch.Size([1, 3, 2, 3])

In [22]:
tensor_3d = y
# Etendre les dimensions pour créer un tensor 4D
data_4d = tensor_3d.unsqueeze(0).repeat(3, 1, 1, 1)
data_4d.shape

torch.Size([3, 3, 2, 3])

## Tensors

In [23]:
import torch

### torch.empty(size): uninitiallized

In [26]:
x = torch.empty(3) # scalar or vector 1d
print(x)
print(x.shape)

tensor([-2.0516e+36,  3.0889e-41, -2.0524e+36])
torch.Size([3])


In [27]:
x = torch.empty(2, 3) # matrix, 2D
print(x)
print(x.shape)

tensor([[-2.0516e+36,  3.0889e-41, -1.8477e+36],
        [ 3.0889e-41,  4.7049e-31,  4.5789e-41]])
torch.Size([2, 3])


In [16]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
print(x)
print(x.shape)

tensor([[[-3.4597e+34,  3.0700e-41,  0.0000e+00],
         [ 7.0065e-45, -3.4636e+34,  3.0700e-41]],

        [[-3.1456e+33,  3.0700e-41,  2.8411e-33],
         [ 4.5799e-41,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 2, 3])


In [28]:
x = torch.rand(2, 2)
print(x)

tensor([[0.2109, 0.0932],
        [0.5810, 0.1365]])


In [29]:
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [30]:
x = torch.ones(2, 2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [31]:
x = torch.ones(2, 2, dtype=torch.double) # torch.float16 ou torch.int
print(x.dtype)

torch.float64


In [32]:
print(x.size())

torch.Size([2, 2])


In [3]:
x = torch.tensor([2.5, 0.1])
print(x.size())

torch.Size([2])


In [10]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

print(x)
print()
print(y)

tensor([[0.4317, 0.3500],
        [0.0597, 0.9835]])

tensor([[0.4243, 0.1411],
        [0.3572, 0.7751]])


In [11]:
z = x + y

print(z)
print()
print(torch.add(x, y))

tensor([[0.8559, 0.4910],
        [0.4169, 1.7586]])

tensor([[0.8559, 0.4910],
        [0.4169, 1.7586]])


In [12]:
z = x - y

print(z)
print()
print(torch.sub(x, y))

tensor([[ 0.0074,  0.2089],
        [-0.2976,  0.2084]])

tensor([[ 0.0074,  0.2089],
        [-0.2976,  0.2084]])


In [14]:
z = x * y 

print(z)
print()
print(torch.mul(x, y))

tensor([[0.1831, 0.0494],
        [0.0213, 0.7623]])

tensor([[0.1831, 0.0494],
        [0.0213, 0.7623]])


In [15]:
z = x / y 

print(z)
print()
print(torch.div(x, y))

tensor([[1.0174, 2.4813],
        [0.1670, 1.2689]])

tensor([[1.0174, 2.4813],
        [0.1670, 1.2689]])


In [ ]:
x = torch.rand

https://www.youtube.com/watch?v=c36lUUr864M&t=462s

https://www.youtube.com/watch?v=V_xro1bcAuA&t=677s