In [2]:
import torch
import numpy as np

## Intro

In [2]:
x = torch.tensor([1, 2, 3])
torch.sum(x)

tensor(6)

**torch.sum(input, dim, keepdim=False, dtype=None) → Tensor**

**numpy.sum(a, axis=None, dtype=None, out=None, keepdims=False)**

In [3]:
x = torch.tensor([
     [1, 2, 3],
     [4, 5, 6]
   ])

x.shape

torch.Size([2, 3])

In [16]:
y = torch.tensor([
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ]
   ])

y.shape

torch.Size([3, 2, 3])

### sum axis=0

![](https://miro.medium.com/v2/resize:fit:640/1*XvGIb1XxF6r9FYHQ3yYPTw.gif)

In [11]:
torch.sum(y, dim=0)

tensor([[ 3,  6,  9],
        [12, 15, 18]])

### sum axis=1

![](https://miro.medium.com/v2/resize:fit:640/1*e608vZqp7jNIdsarKbeunQ.gif)

In [12]:
torch.sum(y, dim=1)

tensor([[5, 7, 9],
        [5, 7, 9],
        [5, 7, 9]])

### sum axis=2

![](https://miro.medium.com/v2/resize:fit:640/1*pf9K7VX2M6_1p39JUmOkLQ.gif)

In [18]:
y

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [17]:
torch.sum(y, dim=2)

tensor([[ 6, 15],
        [ 6, 15],
        [ 6, 15]])

In [20]:
tensor_3d = y
tensor_3d.unsqueeze(0).shape

torch.Size([1, 3, 2, 3])

In [22]:
tensor_3d = y
# Etendre les dimensions pour créer un tensor 4D
data_4d = tensor_3d.unsqueeze(0).repeat(3, 1, 1, 1)
data_4d.shape

torch.Size([3, 3, 2, 3])

## Tensors

In [23]:
import torch

In [26]:
x = torch.empty(3)
print(x)
print(x.shape)

tensor([-2.0516e+36,  3.0889e-41, -2.0524e+36])
torch.Size([3])


In [27]:
x = torch.empty(2, 3)
print(x)
print(x.shape)

tensor([[-2.0516e+36,  3.0889e-41, -1.8477e+36],
        [ 3.0889e-41,  4.7049e-31,  4.5789e-41]])
torch.Size([2, 3])


In [28]:
x = torch.rand(2, 2)
print(x)

tensor([[0.2109, 0.0932],
        [0.5810, 0.1365]])


In [29]:
x = torch.zeros(2, 2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [30]:
x = torch.ones(2, 2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [31]:
x = torch.ones(2, 2, dtype=torch.double) # torch.float16 ou torch.int
print(x.dtype)

torch.float64


In [32]:
print(x.size())

torch.Size([2, 2])


In [3]:
x = torch.tensor([2.5, 0.1])
print(x.size())

torch.Size([2])


In [8]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
z = x + y

print(x)
print()
print(y)
print()
print(z)
print(torch.add(x, y))

tensor([[0.9847, 0.5096],
        [0.2384, 0.9371]])

tensor([[0.2864, 0.0997],
        [0.0562, 0.1131]])

tensor([[1.2711, 0.6093],
        [0.2946, 1.0502]])
tensor([[1.2711, 0.6093],
        [0.2946, 1.0502]])


In [9]:
z = x - y

print(z)
print()
print(torch.sub(x, y))

tensor([[0.6983, 0.4098],
        [0.1822, 0.8240]])

tensor([[0.6983, 0.4098],
        [0.1822, 0.8240]])


In [ ]:
z = x * y 

print(z)
print()
print(torch.sub(x, y))

https://www.youtube.com/watch?v=c36lUUr864M&t=462s

https://www.youtube.com/watch?v=V_xro1bcAuA&t=677s